### Register Request
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "test@test1.com",
  "username": "facuvillo",
  "password": "123456789"
}

### Login Request
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@test1.com",
  "password": "123456789"
}